spring.application.name=botica-demo
server.port=8080

# Base de datos en memoria (se reinicia cada vez que se apaga la app)
spring.datasource.url=jdbc:h2:mem:boticadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ---------------------------------------------------------------------
# BANDERA EDUCATIVA:
# true  -> comportamiento VULNERABLE a Session Fixation (para la demo)
# false -> comportamiento CORREGIDO (regenera el ID de sesion al loguear)
# ---------------------------------------------------------------------
app.security.session-fixation-vulnerable=true

# Configuracion de la cookie de sesion
server.servlet.session.cookie.http-only=true
# Cambiar a "true" si se sirve por HTTPS
server.servlet.session.cookie.secure=false
